### PR TITLE
First working version of auto-deskew

### PR DESCRIPTION
**Pull request by phommel**
Disclaimer: This PR is intended for discussion only

I have just begun to implement a (imho) missing feature: Automatic correction of slightly skewed images. My initial implementation is already working, but I ran into a problem with the LayoutManager of FRotate. I added a new button (btnAutoDeskew) to FRotate. This button gets always pushed downward (presumably by LayoutManager).

misalignedbutton

@cyanfish: Any ideas in regard to why this happens?

### CODE REVIEW

**Comment by cyanfish** [comment]
It's probably because an updated FRotate.resx hasn't been generated for your specific language. See if it works as expected when you select English. If so, then it's just a matter of running the update-language script (though it requires some specific software installed on your computer).

**Comment by phommel** [comment]
Came to a similar conclusion in the meantime. Ran into a similar problem when editing FEditProfile. Already scratched my head as to how you are dealing with resx's. I have a suggestion (in form of my second commit) here: Would it be feasible to deal with this by deleting the position/size properties from the International resx-files? Could be left there for forms that actually have real layout differences in other languages, but should be deletable for all othes. This would make changes easier and not require running a separate script. As to the latter: Is the aforementioned software freely available?

**Comment by cyanfish** [comment]
I don't know if it's possible to do that (and still use the layout designer), but if you can do it and it works feel free.

This software needed (https://www.funduc.com/rtt.htm) is unfortunately not free. You could try it with the evaluation version though. If you do try that, I'd recommend only doing one language at a time, e.g. ".\Update-Language.ps1 de".

**Comment by phommel** [comment]
Is there a convenient way to populate the .po-files in NAPS2.Core\Lang\po with the strings added to the main/english version?

**Comment by phommel** [comment]
Found a way to combine the usage of RTT with my idea of string-only international resxs by post processing RTTs output. Coded a small tool and inserted it into the powershell script. Solves "problem" with eval version of RTT too ;-)

**Comment by phommel** [comment]
Bump: any info the .po-files?

**Comment by cyanfish** [comment]
For the po files - the procedure is to edit the templates.pot file using RTT, upload it to the translation site, and then update them through that interface. This is all something I can do though, I don't think you need to worry about it.

**Comment by cyanfish** [comment]
Hi, I'm interested in including this in the next version of NAPS2. I was just wondering if you've made any other changes before I work on integrating it?

**Comment by cyanfish** [comment]
I've integrated this into NAPS2.

**Pull request closed without merging**
