### PR TITLE
Initial pull for migration to .NET 4.8

### PR DESCRIPTION
**Pull request by unquietwiki**
A while back, we discussed in an e-mail about finally updating this to better support Win 7/10 going forward. I think I figured it out, but there's some Google Auth thing that wasn't completed before, that's holding up further work.

https://github.com/unquietwiki/naps2/tree/develop

### CODE REVIEW

**Comment by unquietwiki** [comment]
Okay... the first 3 commits were clean... the last 5 were trying to get rid of a few files that were stuck in the solution, leftover from getting package info migrated in VS2019. If I could get the git history to merge those into one commit, I would.

**Comment by de-wolff** [comment]
You removed the necessary packages.config from your branch

**Comment by de-wolff** [comment]
> Okay... the first 3 commits were clean... the last 5 were trying to get rid of a few files that were stuck in the solution, leftover from getting package info migrated in VS2019. If I could get the git history to merge those into one commit, I would.

see https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by unquietwiki** [comment]
@de-wolff Thanks for the feedback. For some reason, my environment is wiping out the packages.config from the subfolders. Trying to figure out why that's happening.

**Comment by unquietwiki** [comment]
@de-wolff Okay, that's apparently by design.

https://stackoverflow.com/questions/42293369/missing-packages-config-file

**Comment by unquietwiki** [comment]
@de-wolff I'm going to revoke this pull & revisit. I need to track down why the nuget packages aren't loading correctly; and there might even be room here to pursue .NET Core 3 / .NET 5 migrations; there are some PDFSharp ports on Nuget we could use. Thank you for your patience.

**Pull request closed without merging**
