### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by ostasevych**
Sending updated Ukrainian localisation

### CODE REVIEW

**Comment by ostasevych** [comment]
> Thanks, please upload this through Crowndin (translate.naps2.com)

Is that possible to upload the file with the localisation, which I've attached as a PR?

**Comment by cyanfish** [comment]
Yes, if you've created a Crowdin account, you should be able to go to this link and upload:
https://crowdin.com/project/naps2/translations

**Comment by ostasevych** [comment]
> Yes, if you've created a Crowdin account, you should be able to go to this link and upload: https://crowdin.com/project/naps2/translations

Sadly, when I try to proceed with that page I am getting 403 Forbidden error 
image

**Comment by ostasevych** [comment]
So, I am there. Would you advise, how can I import strings from a file?...

image

**Comment by cyanfish** [comment]
Did you go to that link? You can also see the instructions here:
https://support.crowdin.com/uploading-translations/#uploading-translations-via-translations-tab

**Comment by ostasevych** [comment]
Ah, I do not have access to translations: 403 Forbidden error
image
image

**Comment by cyanfish** [comment]
Hmm, I think I have permissions set up correctly. Does one of these other methods work?
https://support.crowdin.com/uploading-translations/#uploading-translations-via-language-page
https://support.crowdin.com/uploading-translations/#uploading-translations-via-editor

**Comment by ostasevych** [comment]
Updated through crowdin.

**Pull request closed without merging**
